version: "3.1"
services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: amit
      MONGO_INITDB_ROOT_PASSWORD: xTrYISmlThCtmzlU
volumes:
  postgres: ~
